# Generated by Django 4.2.16 on 2024-12-05 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(help_text='ID of the question from the survey JSON')),
                ('question_text', models.TextField(help_text='Text of the question')),
                ('answer', models.TextField(help_text='The answer to the question')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyapp.survey')),
            ],
        ),
    ]
