# Generated by Django 4.2.16 on 2024-12-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0007_alter_questionanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='response',
            field=models.TextField(default=1, help_text='The answer to the question'),
            preserve_default=False,
        ),
    ]
