# Generated by Django 5.1.1 on 2024-12-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0011_survey_cell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='comment_by_admin',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='status_by_admin',
        ),
    ]
