# Generated by Django 4.2.16 on 2024-12-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0002_questionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='action_taken',
            field=models.TextField(blank=True, help_text="Action taken if the answer is 'No'", null=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='issue',
            field=models.TextField(blank=True, help_text="Description of the issue if the answer is 'No'", null=True),
        ),
    ]
