# Generated by Django 4.2.16 on 2024-12-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0005_alter_questionanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=models.TextField(help_text='The answer to the question'),
        ),
    ]
