# Generated by Django 4.2.16 on 2024-12-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0008_questionanswer_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='comment_by_admin',
            field=models.TextField(blank=True, help_text='Comment by admin', null=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='status_by_admin',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', help_text='Status set by admin', max_length=20),
        ),
    ]
