# Generated by Django 4.2.16 on 2024-12-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0010_answer_comment_by_admin_answer_status_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='cell',
            field=models.CharField(default=1, help_text='Cell associated with this survey', max_length=100),
            preserve_default=False,
        ),
    ]
