# Generated by Django 5.1.1 on 2024-12-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0013_answer_user_questionanswer_user_survey_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='answer',
            name='active_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='answer',
            name='sort_order',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='active_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='sort_order',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='active_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='survey',
            name='sort_order',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='survey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
